### ISSUE TITLE
gnome keyring?

### ISSUE THREAD

**Issue by lhazlewood** [gantsign/ansible_role_git_credential_manager#5]
Hi!

Thanks for providing this role - I'm evaluating it currently, but I have a question:

On Linux, the GCM4ML is supposed to delegate to the gnome-keyring, but I don't see gnome-keyring or libsecret as a dependency/requirement installed by any of the ansible tasks in this role.

Is it somewhere that I'm missing?  Any insight would be appreciated.

Thanks!

**Comment by freemanjp** [comment]
Thanks @lhazlewood for raising this issue. As far as I can tell GCM4ML uses [vsts-authentication-library-for-java](https://github.com/Microsoft/vsts-authentication-library-for-java) for storing secrets, which in turn uses [libgnome-keyring](https://github.com/Microsoft/vsts-authentication-library-for-java/blob/5e8335b53eefc7fbfe9e268d155c9cfc40d9810e/storage/src/main/java/com/microsoft/alm/storage/posix/internal/GnomeKeyringLibrary.java#L23). So I've added `libgnome-keyring` as a dependency. Hopefully this resolves your issue.

You can find this change in the [1.1.0](https://github.com/gantsign/ansible_role_git_credential_manager/releases/tag/1.1.0) release of this role. Let me know if you have any further concerns.

Thanks

**Comment by lhazlewood** [comment]
@freemanjp wow!  I was just looking for some pointers to help understand the lay of the land, and you go ahead and make a release!  That's just awesome - thank you! 😄
